extends Node

const SHIP_DATA = {
	"ship_0000" : {
		"ship_name" : "The Prototype",
		"ship_type" : "fighter",
		"ship_max_health" : 50.0,
		"laser_capacity" : 4,
		"carrying_capacity" : 50,
		"texture_path": "res://Assets/Sprites/Spaceships/0014SpaceShip.png",
		"thrust" : 10,
		"deceleration_speed" : 1000,
		"strafe_force" : 500,
		"max_speed" : 1000,
		"thrust_energy_consumption" : 6,
		"rotation_speed": 400,
		"frc" : "frc_0000",
		"collision_shape" : "res://src/Ships/collision_shapes/ship_0000_collision_shape.tscn",
	},
	
	"ship_0001" : {
		"ship_name" : "The Enterprise",
		"ship_type" : "destroyer",
		"ship_max_health" : 200.0,
		"laser_capacity": 9,
		"carrying_capacity" : 1000,
		"texture_path": "res://Assets/Sprites/Spaceships/0024USSEnterprise.png",
		"thrust" : 1000,
		"deceleration_speed" : 2500,
		"strafe_force" : 2000,
		"max_speed" : 3000,
		"thrust_energy_consumption" : 150,
		"rotation_speed": 200,
		"frc" : "frc_0002",
		"collision_shape" : "res://src/Ships/collision_shapes/ship_0001_collision_shape.tscn",
	},
	
	"ship_0002" : {
		"ship_name" : "Freighter 1",
		"ship_type" : "freighter",
		"ship_max_health" : 150.0,
		"laser_capacity" : 0,
		"carrying_capacity" : 10000,
		"texture_path" : "res://Assets/Sprites/Spaceships/0034FreightShip.png",
		"thrust" : 5,
		"deceleration_speed" : 100,
		"strafe_force" : 75,
		"max_speed" : 100,
		"thrust_energy_consumption" : 11,
		"rotation_speed": 100,
		"frc" : "frc_0000",
		"collision_shape" : "res://src/Ships/collision_shapes/ship_0002_collision_shape.tscn",
	},
	
	"ship_0003" : {
		"ship_name" : "Carrier 1",
		"ship_type" : "Carrier",
		"ship_max_health" : 500.0,
		"laser_capacity" : 10,
		"carrying_capacity" : 2000,
		"texture_path" : "res://Assets/Sprites/Spaceships/0052Carrier.png",
		"thrust" : 8,
		"deceleration_speed" : 100,
		"strafe_force" : 75,
		"max_speed" : 500,
		"thrust_energy_consumption" : 11,
		"rotation_speed": 100,
		"frc" : "frc_0001",
		"collision_shape" : "res://src/Ships/collision_shapes/ship_0003_collision_shape.tscn",
	},
	
	"ship_0004" : {
		"ship_name" : "Bubble Prototype",
		"ship_type" : "destroyer",
		"ship_max_health" : 500.0,
		"laser_capacity" : 10,
		"carrying_capacity" : 2000,
		"texture_path" : "res://Assets/Sprites/Spaceships/0063BubbleShipPrototype.png",
		"thrust" : 8,
		"deceleration_speed" : 100,
		"strafe_force" : 75,
		"max_speed" : 500,
		"thrust_energy_consumption" : 11,
		"rotation_speed": 100,
		"frc" : "frc_0001",
		"collision_shape" : "res://src/Ships/collision_shapes/ship_0004_collision_shape.tscn",
	}
}
